INSERT INTO `bot_menu` (`id`, `parent_id`, `name`, `question_id`, `sort`, `is_del`, `deleted_time`, `create_time`, `modify_time`, `row_index`, `target_type`, `helper_title`, `helper_text`, `is_back_enabled`, `back_button_text`) VALUES (11, 1, 'Verification :D', 8, 5, 0, 0, 0, 0, 1, 2, 'Verification', 'verification', 1, 'Back');
INSERT INTO `bot_menu` (`id`, `parent_id`, `name`, `question_id`, `sort`, `is_del`, `deleted_time`, `create_time`, `modify_time`, `row_index`, `target_type`, `helper_title`, `helper_text`, `is_back_enabled`, `back_button_text`) VALUES (12, 2, 'Verified or Unverified User?', 9, 4, 0, 0, 0, 0, 2, 2, 'Verified or Unverified User', '', 1, 'Back');


INSERT INTO `bot_question` (`id`, `scene_type`, `helper_title`, `title`, `helper_text`, `frontend_type`, `max_multi_len`, `sort`, `matching_mode`, `matching_question_id`, `is_del`, `deleted_time`, `create_time`, `modify_time`) VALUES (8, 1, 'Verification', 'Do you have a NUS email address? ', 'Press verify to ensure you get matched with NUS students! If you remain unverified, you may not be able to find a match. Your email will be anonymous to other users.', 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `bot_question` (`id`, `scene_type`, `helper_title`, `title`, `helper_text`, `frontend_type`, `max_multi_len`, `sort`, `matching_mode`, `matching_question_id`, `is_del`, `deleted_time`, `create_time`, `modify_time`) VALUES (9, 2, 'Verified or Unverified User?', 'Who do you want to match with?', 'You can choose to match only with verified NUS students, or even those who are unverified. ', 1, 0, 0, 1, 0, 0, 0, 0, 0);


INSERT INTO `bot_option` (`id`, `question_id`, `option_type`, `label`, `value`, `is_matching_any`, `sort`, `is_del`, `deleted_time`, `create_time`, `modify_time`, `row_index`, `matching_option_id`) VALUES (46, 8, 1, 'Verify! :D', 'verify', 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `bot_option` (`id`, `question_id`, `option_type`, `label`, `value`, `is_matching_any`, `sort`, `is_del`, `deleted_time`, `create_time`, `modify_time`, `row_index`, `matching_option_id`) VALUES (47, 8, 1, 'Remain unverified :(', 'remain unverified', 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `bot_option` (`id`, `question_id`, `option_type`, `label`, `value`, `is_matching_any`, `sort`, `is_del`, `deleted_time`, `create_time`, `modify_time`, `row_index`, `matching_option_id`) VALUES (48, 9, 1, 'Verified Students! :D', 'verified students', 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `bot_option` (`id`, `question_id`, `option_type`, `label`, `value`, `is_matching_any`, `sort`, `is_del`, `deleted_time`, `create_time`, `modify_time`, `row_index`, `matching_option_id`) VALUES (49, 9, 1, 'Unverified Users', 'unverified users', 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `bot_option` (`id`, `question_id`, `option_type`, `label`, `value`, `is_matching_any`, `sort`, `is_del`, `deleted_time`, `create_time`, `modify_time`, `row_index`, `matching_option_id`) VALUES (50, 9, 1, 'Anything!', 'anything', 0, 0, 0, 0, 0, 0, 1, 0);
